/**
 * Generates apps/app/src/environments/environment.ts from the root .env so the
 * Angular browser bundle can use the SAME .env as Elysia.
 *
 * Browsers have no process.env, so env values must be baked in at build time.
 * Only the keys in PUBLIC_KEYS below are exposed — this is the allowlist that
 * keeps server secrets OUT of the browser bundle. To expose a new var to the
 * frontend, add its name here (and never add a secret). Bun auto-loads .env
 * before running this, so process.env already holds the values.
 *
 * Runs automatically before dev:app / build:app; or manually: `bun run env:generate`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/** Env vars exposed to the Angular browser bundle. PUBLIC — never secrets. */
const PUBLIC_KEYS = ['API_URL', 'APP_NAME'] as const;

const OUT = join(import.meta.dir, '../apps/app/src/environments/environment.ts');

/** API_URL -> apiUrl */
const camelCase = (key: string): string =>
  key.toLowerCase().replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const entries = PUBLIC_KEYS.map(
  (key) => [camelCase(key), process.env[key] ?? ''] as const,
).sort(([a], [b]) => a.localeCompare(b));

const body = entries.map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`).join('\n');

const contents = `// GENERATED by scripts/generate-env.ts — do not edit.
// Source: root .env (allowlisted PUBLIC_KEYS). Regenerate: \`bun run env:generate\`.
export const environment = {
${body}
} as const;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, contents);

console.log(`✓ environment.ts generated from .env (${entries.length} public var(s))`);
